#!/bin/bash
set -euo pipefail
# SPDX-FileCopyrightText: 2026 Harald Pretl
# Johannes Kepler University, Department for Integrated Circuits
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
#
# Run LVS on toplevel; we take the schematic netlist generated by the toplevel Librelane
# flow, and the layout netlist generated by magic, and run LVS on them. The LVS result is
# written to lvs.out.

SCH_NETLIST="tinywhisper_top.spice"
SCH_TOPCELL="tinywhisper_top"
#SCH_TOPCELL="riscv_top"
#SCH_TOPCELL="iqmod_top"
LAY_NETLIST="SoC4219_fixed_hierarchy.ext.spice"
LAY_TOPCELL="tinywhisper_top"
#LAY_TOPCELL="riscv_top"
#LAY_TOPCELL="iqmod_top"

SPICE_LIBS="sg13g2_io.spi sg13g2_stdcell.spice riscv_top.spice iqmod_top.spice"
#SPICE_LIBS="sg13g2_io.spi sg13g2_stdcell.spice"

# Check that all required input files exist
err=0
for f in "$SCH_NETLIST" "$LAY_NETLIST"; do
    if [ ! -f "$f" ]; then
        echo "[ERROR] Input file not found: $f" >&2
        err=1
    fi
done
for f in $SPICE_LIBS; do
    if [ ! -f "$f" ]; then
        echo "[ERROR] Library file not found: $f" >&2
        err=1
    fi
done
for f in check_floating_nets.py merge_spice.py remove_dollar1.sh; do
    if [ ! -f "$f" ]; then
        echo "[ERROR] Helper script not found: $f" >&2
        err=1
    fi
done
if [ -z "$PDKPATH" ] || [ ! -f "$PDKPATH/libs.tech/netgen/ihp-sg13g2_setup.tcl" ]; then
    echo "[ERROR] PDKPATH not set or netgen setup file not found: \$PDKPATH/libs.tech/netgen/ihp-sg13g2_setup.tcl" >&2
    err=1
fi
[ "$err" -ne 0 ] && exit 1

# Copy input netlists locally, stripping any directory paths
SCH_LOCAL="$(basename "$SCH_NETLIST")"
LAY_LOCAL="$(basename "$LAY_NETLIST")"
[ "$SCH_NETLIST" != "$SCH_LOCAL" ] && cp "$SCH_NETLIST" "$SCH_LOCAL"
[ "$LAY_NETLIST" != "$LAY_LOCAL" ] && cp "$LAY_NETLIST" "$LAY_LOCAL"

# The layout netlist is generated by magic, and it contains stray dollar-1 in 
# some instance names. We clean that first.

#echo "[INFO] Removing \$1 from layout netlist instance names..."
./remove_dollar1.sh "$LAY_LOCAL" "${LAY_LOCAL}.tmp1"

# There could be unconnected pins on subcircuit instances; this confuses netgen.
# We remove this pins from the layout netlist hierarchically.

python3 check_floating_nets.py "${LAY_LOCAL}.tmp1" --top "${LAY_TOPCELL}" \
    --fix-ports \
    --output "${LAY_LOCAL}.tmp2"

# The schematic netlist created by the toplevel Librelane flow may contain stubs.
# We first replace the stubs (blackboxes) with the actual subcircuit definitions
# from the libraries.

python3 merge_spice.py "${SCH_LOCAL}" \
    ${SPICE_LIBS} \
    -o "${SCH_LOCAL}.tmp1"

# There could be unconnected pins on subcircuit instances; this confuses netgen.
# We remove this pins from the schematic netlist hierarchically.

python3 check_floating_nets.py "${SCH_LOCAL}.tmp1" --top "${SCH_TOPCELL}" \
    --fix-ports \
    --output "${SCH_LOCAL}.tmp2"

# Now we are ready to run LVS. We use the IHP SG13G2 PDK setup for netgen, which is compatible with our design.

netgen -batch lvs \
    "${LAY_LOCAL}.tmp2 ${LAY_TOPCELL}" \
    "${SCH_LOCAL}.tmp2 ${SCH_TOPCELL}" \
    "$PDKPATH/libs.tech/netgen/ihp-sg13g2_setup.tcl" \
    lvs.out

# Clean up temporary files
rm -f "${SCH_LOCAL}.tmp1" "${SCH_LOCAL}.tmp2" "${LAY_LOCAL}.tmp1" "${LAY_LOCAL}.tmp2"
